### PR TITLE
Contraint horizontally widgets

### PR DESCRIPTION
**Pull request by herou**
I found out that two widgets were not constraint horizontally.

### CODE REVIEW

**Comment by rafaelekol** [comment]
In case we set constraints horizontally we'd better use "0dp" as width, not "match_parent".

**Comment by abdrasulov** [comment]
Hi @herou! Can you please re-send this PR to `version/0.19`? We've recently merged `version/0.18` into master. And it seems that github automatically closed all pending PR to this branch.

**Comment by herou** [comment]
Yes, sure.

**Comment by herou** [comment]
@abdrasulov You have it: #2935

**Pull request closed without merging**
