### PR TITLE
Keyboard custom dialog

### PR DESCRIPTION
**Pull request by herou**
-redesigned the keyboard as in the mockup
-if the user clicked skipped, I use the shared preference to store it and not showing the keyboard alert anymore

### CODE REVIEW

**Comment by abdrasulov** [comment]
Hi @herou. Thanks for making a contribution to our app. We have reviewed your PR and we have the following comments:

1. Please use the current working branch that is version/0.18 instead of master. Sorry, we missed to mention it in our contribution guide. We've done it after your PRs.

Regarding the feature implementation itself:

1. The third-party keyboard should be allowed only after the user has chosen "skip". As of now, it starts to allow it even if the user dismisses the dialog.
1. Based on the previous point it's better to set the setting name as "isThirdPartyKeyboardAllowed".
1. MainSettingsPresenter is intended to be used in its own fragment MainSettingsFragment. So the logic for storing the setting should be not there. I see the AlertDialogKeyboardFragment as a good candidate for this since it is created especially for this feature. You can interact with thirdKeyboardStorage right there via App.thirdKeyboardStorage.

**Comment by abdrasulov** [comment]
One more point. There is RestoreEosFragment that also shows third party keyboard alert. It should be updated too

**Comment by herou** [comment]
@abdrasulov 
Regarding points 2 and 3 I am okay with you. Regarding point #1 I did not get you

image

This is how it works now. If the user clicked skipped the keyboard alert will not show up again. Am I missing something?

**Comment by herou** [comment]
@abdrasulov Regarding point 3.
AlertDialogKeyboardFragment is part of the Views component and It needs the import the app component in order to access the App Class. If I import the app component into Views grandle:  implementation project(':app') the project will not compile because of this error: 

image

How can I access the App class inside the Views component?

**Comment by abdrasulov** [comment]
@herou, I got it. In this case, I'd suggest to implement it via AlertDialogKeyboardFragment.Listener interface. Add a new method to this interface that will be called when the Skip button is clicked. Since the implementations of this listener are going to be in the "app" module they should have access to the App instance.

It worth noting that this part of the code is a little bit expired. Usually, we access the App instance only when initializing the Services/Interactors. As of now, we can use it in the activity/fragment layer for the third-party keyboard feature as an exceptional case.

**Comment by herou** [comment]
@abdrasulov  New PR has been created.

**Pull request closed without merging**
