### PR TITLE
Zcash/update sdk 1.3.0 beta16

### PR DESCRIPTION
**Pull request by gmale**
Changes to update to the latest Android SDK. This adds quite a lot of [changes and fixes since version 1.2.1-beta04](https://github.com/zcash/zcash-android-wallet-sdk/blob/master/CHANGELOG.md#version-121-beta04-2021-01-05), including migrating to Maven Central from JCenter (this also adds t-addr support and autoshielding support, under the hood)

Tasks to complete before converting this from a DRAFT to a PR:

- [x] Add latest SDK
- [x] Update and fix all breaking changes listed in [migration guide](https://github.com/zcash/zcash-android-wallet-sdk/blob/master/MIGRATIONS.md#migrating-to-version-13-from-12)
- [x] Switch to new lightwalletd.com server for testnet connections
- [x] Remove the use of GlobalScope to prevent leaks and other errors
- [x] Update the Send workflow so that it waits for transactions to complete and also shows errors
- [x] Update the verification-metadata.xml
- [x] Test and verify on testnet both for successful and failed transactions
- [x] Test and verify on mainnet

### CODE REVIEW

**Comment by gmale** [comment]
I just released 1.3.0-beta16 an hour ago. Once that shows up on [our MavenCentral repo](https://search.maven.org/artifact/cash.z.ecc.android/zcash-android-sdk), this PR will be ready to go.

**Comment by gmale** [comment]
Testing complete. PR is ready for review.

**Comment by gmale** [comment]
Note: `gradle/verification-metadata.xml` has some issues that prevent the build from compiling because I only touched the Zcash parts of that file. I could regenerate the whole thing but I wasn't sure if that would cause conflicts or if it would match the hashes that Unstoppable wants to use, so I left it alone.

Delete, rename or regenerate that file in order to run the build.

**Comment by gmale** [comment]
**Important note:** The easiest place to test is on Testnet and you can send yourself funds from one of these Testnet faucets:

https://faucet.testnet.z.cash/
https://faucet.zecpages.com/

**Review by omurovch — APPROVED** [review]

**Review by rafaelekol — APPROVED** [review]

**Review by omurovch — APPROVED** [review]

**Review by rafaelekol — APPROVED** [review]

**Comment by omurovch** [comment]
#3890

**Pull request merged**
