### PR TITLE
Third Keyboard custom dialog 

### PR DESCRIPTION
**Pull request by herou**
Developed the third keyboard feature.

### CODE REVIEW

**Comment by abdrasulov** [comment]
Cool, great! A few more points:

1. The same dialog should be shown for RestoreEosFragment. As of now, it shows the old one.
1. (optional) When the BaseFragment has an updated `showCustomKeyboardAlert` method, we'll be able to use it also for RestoreWordsFragment. So we can remove the method `showCustomKeyboardAlert` in BaseActivity.
1. Rephrase commit messages based on https://chris.beams.io/posts/git-commit/#seven-rules
1. There are some conflicts. They should be resolved.

**Comment by herou** [comment]
@abdrasulov
1- I am showing the new dialog in RestoreEosFragment.
2- I found another solution, In RestoreEosFragment I am showing the dialog from BaseActivity and the method showCustomKeyboardAlert in BaseFragment was never used, so I had to delete it. Is it okay?
3- I Rephrased all my commit-msg (I hope they are okay)
4- I resolved the merging.

**Comment by herou** [comment]
@abdrasulov  If this PR is okay I would like to help with other tickets as well :) I am really enjoying contributing to this repo.

**Comment by abdrasulov** [comment]
@herou, it's great to hear :)

**Comment by abdrasulov** [comment]
@herou, it's great to hear that :)

As for point 2, I think it's better to have it in the BaseFragment. It makes fragments a little more independent from the activity.

**Comment by abdrasulov** [comment]
@herou, it's great to hear that :)

As for point 2, I think it's better to have it in the BaseFragment. It makes fragments a little more independent from the activity.

As for git commit, we're going to describe our git flow in the contribution guide in detail. For now, we'll merge your PR via the squash method when it's ready.

**Comment by herou** [comment]
@abdrasulov  Point 2 is done as you asked.

**Review by abdrasulov — APPROVED** [review]

**Comment by herou** [comment]
@abdrasulov Can I have something else to take care of?

**Review by rafaelekol — APPROVED** [review]

**Comment by herou** [comment]
@rafaelekol  @abdrasulov Thank you for approving my PR.

**Comment by abdrasulov** [comment]
@herou, Good job! Thanks.

We'll check our backlog for tickets that we can give you.

**Comment by herou** [comment]
@abdrasulov Hi, please tell me if you find something for me.

**Comment by abdrasulov** [comment]
Hi @herou. There is no ticket that we can give you at the moment. We'll work on that next week. There were thoughts about refactoring related to layouts. We'll let you know.

**Comment by herou** [comment]
> Hi @herou. There is no ticket that we can give you at the moment. We'll work on that next week. There were thoughts about refactoring related to layouts. We'll let you know.
@abdrasulov I see. Well, at least I will have something to contribute next week :). As an experienced team of blockchain can I ask you privately? If you wish, write to me at elioprifti@gmail.com

**Comment by abdrasulov** [comment]
Hi @herou. You can take this issue #2588 if you are interested

**Comment by herou** [comment]
@abdrasulov Done it, what's next?

**Pull request merged**
