### PR TITLE
Add `Rootstock` network

### PR DESCRIPTION
**Pull request by ahsan-javaiid**
### Description
This PR adds `rootstock` network along with send / receive `RBTC` + RIF (ERC20) token to unstoppable money wallet.

### Demo Snapshot
 
Screenshot 2023-10-12 at 12 05 13 PM

### Demo Video

https://github.com/horizontalsystems/unstoppable-wallet-android/assets/104683677/04ddab9b-cf1b-4893-a2a6-56441d853481

### How to test
- Import or create wallet and select `Rootstock RSK`
- Import `RIF` erc20 token and send / receive

Feel free to review and consider pull request or suggest any changes.

### CODE REVIEW

**Comment by ahsan-javaiid** [comment]
Hi @Dianaaiym @rafaelekol 
Any thought's on considering the `Rootstock integration`: @Dianaaiym @rafaelekol

**Comment by rafaelekol** [comment]
We have made the decision to limit the addition of new blockchains to an internal process. This is because, once a blockchain is added, we commit to maintaining it diligently. Therefore, we will not be able to accept your pull request at this time. However, we encourage you to fork our repository and implement your changes independently.

**Comment by ahsan-javaiid** [comment]
Hi @rafaelekol

`Rootstock` is EVM compatible chain so i believe there will be as such no maintenance required or we will take care of it.  We really like to discuss the Rootstock addition with business team. Would be great if you can share contact/telegram to setup a meeting to discuss it further.

**Comment by Dianaaiym** [comment]
> Hi @rafaelekol
> 
> `Rootstock` is EVM compatible chain so i believe there will be as such no maintenance required or we will take care of it. We really like to discuss the Rootstock addition with business team. Would be great if you can share contact/telegram to setup a meeting to discuss it further.

Hi @ahsan-javaiid 

Thank you for your interest. We've responded to your query via email with further details.

**Pull request closed without merging**
