### PR TITLE
Fixed typo in README.md

### PR DESCRIPTION
**Pull request by snemes**

### CODE REVIEW

**Review by abdrasulov — DISMISSED** [review]

**Comment by abdrasulov** [comment]
Hello, @snemes. Can you please make PR to the branch `version/0.26` instead of `master`?

**Comment by Athayde3586** [comment]
What's going on here

**Comment by snemes** [comment]
> Hello, @snemes. Can you please make PR to the branch version/0.26 instead of master?

Done.

**Comment by Athayde3586** [comment]
Please stop ur dam games

**Comment by snemes** [comment]
@Athayde3586 

You've been reported as a spam account for your unrelated and unrelevant comments on this pull request.

**Comment by Athayde3586** [comment]
Really the spammer is u

**Comment by Athayde3586** [comment]
So why r u trying to blame me for ur actions

**Comment by Athayde3586** [comment]
So look leave . Y stuff alone I have asked plenty of times

**Comment by Athayde3586** [comment]
Like I said stop messing with my stuff

**Comment by snemes** [comment]
I created a brand new pull request on top of the version/0.26 branch just to be able to keep things nice and clean (instead of the just editing the PR to change the base branch).

See #5054

**Pull request closed without merging**
