### PR TITLE
Fix deleting of an unrecoverable keystore key.

### PR DESCRIPTION
**Pull request by Tameki**

### CODE REVIEW

**Comment by rafaelekol** [comment]
How do you reproduce this bug?

**Comment by Tameki** [comment]
Tested on Android 8.1.0 and 9 (Samsung Galaxy Tab and S8):
- Create or restore wallet
- Close app
- Reset system lock to "Swipe" (with data removing)
- Set new PIN
- Open app

Seems that Android 10 has already fixed this issue.

**Comment by Tameki** [comment]
> How do you reproduce this bug?

Tested on Android 8.1.0 and 9 (Samsung Galaxy Tab and S8):
- Create or restore wallet
- Close app
- Reset system lock to "Swipe" (with data removing)
- Set new PIN
- Open app
Seems that Android 10 has already fixed this issue.

**Comment by rafaelekol** [comment]
#1809

**Pull request closed without merging**
