### PR TITLE
renamed Today to TDY (СГД)

### PR DESCRIPTION
**Pull request by herou**
As #2814 is describing:

### CODE REVIEW

**Comment by Dianaaiym** [comment]
You only need to rename 'today' to 'TDY'
'СГД' it is translation into Russian language, it should be fixed in another localization file

**Comment by herou** [comment]
> You only need to rename 'today' to 'TDY'
> 'СГД' it is translation into Russian language, it should be fixed in another localization file

okay, got it.

**Comment by herou** [comment]
@Dianaaiym  you have it.

**Comment by tmedetbekov** [comment]
@herou we use the `master` branch as release branch. Seems like your local master branch is outdated and this PR contains some duplicated commits which are already in `version/18` branch. Can you re-create this PR from the `version/0.18` branch?

**Comment by herou** [comment]
> @herou we use the `master` branch as release branch. Seems like your local master branch is outdated and this PR contains some duplicated commits which are already in `version/18` branch. Can you re-create this PR from the `version/0.18` branch?

Yes, created a new PR for this: #2837. I hope this time works.

**Comment by herou** [comment]
> @herou we use the `master` branch as release branch. Seems like your local master branch is outdated and this PR contains some duplicated commits which are already in `version/18` branch. Can you re-create this PR from the `version/0.18` branch?

Created a new PR  #2837 and closing this one.

**Pull request closed without merging**
